name: vercel deploy using git actions
on:
  push:
    branches: [ dev, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # deploy app to vercel
    - name: dev-deploy-vercel
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        github-token: ${{ secrets.REPO_TOKEN }} #Optional 
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required\
        
    - name: deploy-vercel
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        github-token: ${{ secrets.REPO_TOKEN }} #Optional 
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
